import Head from "next/head";
import Image from "next/image";
import constructionPic from "../public/construction.jpg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <h1>DYNAMIC BCS</h1>
      </nav>

      <main className={styles.main}>
        <Image layout="intrinsic" src={constructionPic} />
      </main>

      <footer className={styles.footer}>
        <div className={styles["footer-misc"]}>
          <div className={styles["footer-misc-social"]}>
            <h2>Follow us</h2>
            <a>Instagram</a>
            <a>Twitter</a>
            <a>Facebook</a>
          </div>
          <div className={styles["footer-misc-section"]}>
            <h2>Other links</h2>
            <a
              href="https://www.freepik.com/vectors/background"
              target="_blank"
              rel="noreferrer"
            >
              Art{" "}
            </a>
            <a
              href="https://www.freepik.com/vectors/background"
              target="_blank"
              rel="noreferrer"
            >
              Design{" "}
            </a>
          </div>
          <div className={styles["footer-misc-contact"]}>
            <div>
              <h2>Call us</h2>
              <div className={styles["phone-number"]}>
                <p>Phone Number:</p>
                <h3>(415)767-6551</h3>
              </div>
              <div className={styles["phone-number"]}>
                <p>e-mail:</p>
                <h3>dynamicbcs@gmail.com</h3>
              </div>
            </div>
          </div>
        </div>
        <p className={styles["footer-foot-note"]}>
          © 2021 Dynamic Black Car Services. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
